name: Publish Extension

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build and Package
        run: node scripts/publish.js
      
      - name: Upload VSIX as artifact
        uses: actions/upload-artifact@v4
        with:
          name: taskboard-extension
          path: "*.vsix"
      
      - name: Publish to Marketplace
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          node scripts/publish.js --publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }} 